#!/bin/sh

if test $# -ne 0
then if test $1 = "-h" -o  $1 = "-help" -o $1 = "--h" -o $1 = "--help"
     then echo "$0 [-no] [-h|-help]"
          exit
     fi
fi

clean=""

if test $# -ne 0
then if test $1 = "-no"
     then clean=clean
     fi
fi

cd LibAgents2D/src
make $clean
cd ../../..
